### ISSUE TITLE
Can we get the navbar added

### ISSUE THREAD

**Issue by Cypher1** [surprisetalk/elm-bulma#1]
Spec is here
http://bulma.io/documentation/components/navbar/

Would be great to have this added. I'd create a PR but I'm very new to Bulma.

If you like I can open a PR with my guess at what needs to happen.

Thanks

**Comment by surprisetalk** [comment]
Hello! No need to make a PR. I'll add the navbar tonight :)

**Comment by surprisetalk** [comment]
Hi @Cypher1, sorry for the ridiculous delay.
I know you're probably not interested anymore, but I thought I'd let you know that I just committed a potential `navbar` solution -- I'd love for you to look over it before I publish to Elm Packages.
You can find it [here](https://github.com/surprisetalk/elm-bulma/blob/master/src/Bulma/Components.elm).

**Comment by Cypher1** [comment]
Ohh that's good news. I've actually been playing with static sites in Hakyll in the mean time.
Thanks for the update. I'll see if I can get back to my elm work soon.

**Comment by surprisetalk** [comment]
It's been a long time, but I finally published a huge update to this package! Closing this issue -- thanks for the support!
