### ISSUE TITLE
Table row is always selected

### ISSUE THREAD

**Issue by mattiast** [surprisetalk/elm-bulma#11]
https://github.com/surprisetalk/elm-bulma/blob/3c2f6b4563bfbf8258b26fe5f2eb150c44694ecd/src/Bulma/Elements.elm#L723-L728

**Comment by surprisetalk** [comment]
Thanks! Fixed and published to Elm Packages in Elm-Bulma 6.0.2.

**Comment by mattiast** [comment]
Great, that was quick
