### ISSUE TITLE
any plan to add carousel?

### ISSUE THREAD

**Issue by tdxiong** [surprisetalk/elm-bulma#15]
https://wikiki.github.io/components/carousel/

This one looks good for fancy pages, any plan to add it?

Thanks

**Comment by surprisetalk** [comment]
The Bulma Extensions are great, but I haven't thought of a clean way to add them into the Elm-Bulma package yet. 

If you're interested, I could make a little carousel snippet that you could copy-and-paste into your project.  

If you've already implemented the carousel in Elm, I'd love to see it! It could be a useful template for others who are looking to do similar work.

**Comment by tdxiong** [comment]
I've not implemented it yet. Thank you.
