### ISSUE TITLE
Please update to Bulma 0.6.0

### ISSUE THREAD

**Issue by dbj** [surprisetalk/elm-bulma#2]
Please update to Bulma 0.6.0.  Thanks.

**Comment by surprisetalk** [comment]
Hello @dbj !
Sorry for the long delay. I've updated the library to `0.6.2`, if you're still interested.
I haven't published to Elm Packages yet, so feel free to look over the code and make suggestions.
Thanks!

**Comment by surprisetalk** [comment]
Updated to `0.6.2`! Enjoy!
