### ISSUE TITLE
Why is there no `Width12` in Width type?

### ISSUE THREAD

**Issue by uzimaru0000** [surprisetalk/elm-bulma#20]
Hi
Currently, Width type has `Auto` , `Width1` ~ `Width11` .
However, Bulma supports `is-12` . Why is there no `Width12` in Width type?
Please tell me if there is a workaround you do not need.

**Comment by surprisetalk** [comment]
Hmmm. Are there any cases where `Width12` and `Auto` aren't the same? I was trying to simplify the API, but I may have been too heavy-handed...

**Comment by uzimaru0000** [comment]
For example, you want to set the column size to `Width12` and` Width8`. However, there is no `Width12` in the Width type, so `Auto` will result in one line.

![2018-11-13 11 56 06](https://user-images.githubusercontent.com/13715034/48474083-266b1080-e83d-11e8-914d-5e0b5d0f68a5.png)
`Width12` and `Width8`

![2018-11-13 11 56 21](https://user-images.githubusercontent.com/13715034/48474094-2a972e00-e83d-11e8-820e-1d03f175377f.png)
`Auto` and `Width8`

**Comment by surprisetalk** [comment]
In the first case, wouldn't you just use two `columns` containers? The first would have one column (`Auto`) and the second would contain the other column (`Width8`).

Is it common practice to use `Width12` to "push" other columns off the edge into new rows?

**Comment by uzimaru0000** [comment]
That makes sense! Certainly it may be nice to keep a simple API.
I have solved the problem. Thank you!!
