### ISSUE TITLE
Example doesn't work without changes

### ISSUE THREAD

**Issue by Razzeee** [surprisetalk/elm-bulma#3]
I'm getting all sorts of errors when trying to follow https://github.com/surprisetalk/elm-bulma#getting-started regarding to the code example

**Comment by zainhoda** [comment]
I found this issue as well. This code below worked for me:

```
module Main exposing (..)

import Bulma.CDN exposing (..)
import Bulma.Elements exposing (..)
import Bulma.Grid as Grid exposing (..)
import Bulma.Layout exposing (..)
import Html
    exposing
        ( Html
        , main_
        , text
        )


type Model
    = NoModel


main =
    Html.beginnerProgram
        { model = NoModel
        , view = view
        , update = \msg -> \model -> model
        }


view : Model -> Html msg
view model =
    main_ []
        [ stylesheet
        , section Spaced [] [ exampleHero ]
        , section Spaced [] [ exampleGrid ]
        ]


exampleHero : Html msg
exampleHero =
    Grid.columns columnsModifiers
        []
        [ hero heroModifiers
            []
            [ heroBody []
                [ container []
                    [ title H1 [] [ text "Hero Title" ]
                    , title H2 [] [ text "Hero Subtitle" ]
                    ]
                ]
            ]
        ]


exampleGrid : Html msg
exampleGrid =
    Grid.columns columnsModifiers
        []
        [ column columnModifiers [] [ text "First Column" ]
        , column columnModifiers [] [ text "Second Column" ]
        , column columnModifiers [] [ text "Third Column" ]
        ]
```

**Comment by surprisetalk** [comment]
Thanks @Razzeee and @zainhoda !
Sorry for the sloppy work.
I upgraded the entire package to `0.6.2` this weekend, and added a lot of features! And this time I've double-checked that the README example is accurate :)
I'll likely be publishing the code to Elm Packages tomorrow, so feel free to make any other suggestions before then, and I'll try to get them in.
Thanks!

**Comment by windpeoples** [comment]
If and when you have the time and inclination to publish the code to Elm Packages I'd be much obliged. I am considering elm-bulma for a project. Thanks!

**Comment by surprisetalk** [comment]
Just finished my changes and published to Elm Packages. You can find a giant example file [here](https://github.com/surprisetalk/elm-bulma/blob/master/src/Example.elm).
Thanks for the continued feedback and support everyone!
